name: Build and Deploy VitePress

on:
  push:
    paths:
      - 'apps/documentation/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npm run docs:build

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Automated build and deploy from GitHub Actions"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
